apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-test
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: envs/test
    repoURL: https://github.com/RHC-STP-OSSM/gitops-app-bookinfo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
